### ISSUE TITLE
Create Navigation Bar Section

### ISSUE THREAD

**Issue by freeCodeCampLisbon** [freeCodeCampLisbon/landing-page#1]

**Comment by pedropcruz** [comment]
@amritpoudel11 congratz for your effort!

Your next step, it's doing some javascript. On your navigation bar, when i scrolll to the end of your HeroSection, you need to give a new class, that change your logo image, add a background on navbar and change the colours on your nav-links. Good luck on that! :)

**Comment by pedropcruz** [comment]
@amritpoudel11 when you are changing on scroll, you need to change the hamburguer as well. As you can see on this print:
![image](https://user-images.githubusercontent.com/6757946/41880956-c562a9b6-78d8-11e8-8504-7c87af8a53d8.png)

**Comment by amritpoudel11** [comment]
fixed both issues :)
