### ISSUE TITLE
Links from Footer

### ISSUE THREAD

**Issue by pedropcruz** [freeCodeCampLisbon/landing-page#15]
On hover them, you have a little text-decoration. Just remove it as well, and you can put them a little bigger as well

**Comment by amritpoudel11** [comment]
already fixed the text-decoration but do you mean I should make the whole footer bigger or you mean just the social media icons?

**Comment by pedropcruz** [comment]
just social media icons. and i forgot to mention, on Hero Section as well.

**Comment by amritpoudel11** [comment]
fixed both the issues. thanks. 👍
